### ISSUE TITLE
Will it work in Debian?

### ISSUE THREAD

**Issue by marshallovski** [mcgillij/amdfan#30]
Linux 6.1
drivers: `amdgpu`

Hi, I have a problem with my RX580 coolers. `sensors` and LACT (https://github.com/ilya-zlobintsev/LACT) gives me "0 RPM". Does amdfan will work on Debian 12?

![зображення](https://github.com/mcgillij/amdfan/assets/68496774/865db72b-21dc-446a-93c0-63ad532b62ab)

**Comment by mcgillij** [comment]
You can always try it out, by default I just package it for Arch, but it's just a python script. It rely's on /sys/class/drm/* being populated properly with you're cards info.

**Comment by marshallovski** [comment]
Okay, thank you!
